name: graphql-base-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - uvicorn
  - pytest
  - pytest-asyncio
  - make
  - Django>=5.0,<6.0
  - strawberry-graphql
  - aiodataloader
   

